apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-deployment
spec:
  replicas: 2 # Number of desired replicas
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
      - name: swiggy
        image: pavan5763/swiggy-project:latest
        ports:
        - containerPort: 3000  # Port your application listens on