apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
  labels:
    app: hotstar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hotstar
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
      - name: hotstar-container
        image: 211125314839.dkr.ecr.us-east-1.amazonaws.com/hotstar:latest
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: hotstar-service
  labels:
    app: hotstar
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30036
  selector:
    app: hotstar
